apiVersion: apps/v1
kind: Deployment #https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#deploymentspec-v1-apps
metadata:
  name: sbservice2dep
spec:
  replicas: 2
  selector:
    matchLabels:
      type: backend
#  minReadySeconds: 1
#  progressDeadlineSeconds: 60
#  revisionHistoryLimit: 5
#  strategy:
#    type: RollingUpdate #The other normal option is Recreate
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 1
  template:
    metadata:
      name: sbservice2rs
      labels:
        type: backend
    spec:
      containers:
      - name: sbservice2cont
        image: sbservice2img:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
#        ports:
#          - containerPort: 8080
        readinessProbe:
            httpGet:
              path: /sbservice2/hello
              port: 8080
        livenessProbe:
            httpGet:
              path: /sbservice2/hello
              port: 8080
            initialDelaySeconds: 2
---

apiVersion: v1
kind: Service
metadata:
  name: sbservice2svc
spec:
  type: NodePort
  selector:
    type: backend
  ports:
  - port: 8080 # PODS port
    nodePort: 30001 # The port on which the service can be accessed using node IP
